### ISSUE TITLE
Typescript errors when building my project

### ISSUE THREAD

**Issue by NathanBeddoeWebDev** [JustinBeckwith/gaxios#48]
I am attempting to build my Node.js and typescript project, and am running into a couple of issues.

node_modules/gaxios/build/src/index.d.ts(22,12): error TS1005: '>' expected.
node_modules/gaxios/build/src/index.d.ts(22,49): error TS1109: Expression expected.

gaxios is being used as a dependency of Google-Auth-Library and it's using version 1.2.1.

Is there a fix I can make myself for this?

**Comment by JustinBeckwith** [comment]
Greetings!  What version of TypeScript and Node.js are you using?

**Comment by leonardpunt** [comment]
I hit the same issue using TypeScript 2.8.1 and Node.js 8.11.3

**Comment by JustinBeckwith** [comment]
Thanks!  Could you try the latest version of TypeScript?  This is really only compiled on the latest version.

**Comment by leonardpunt** [comment]
There is no issue on the latest version TypeScript version ^3.3.0. However, I was hoping there would an alternative solution to upgrading the TypeScript version, since that requires quite some work in our current project.

**Comment by JustinBeckwith** [comment]
Yeah, apologies - that's just not something we're going to be able to support :/  We're pretty aggressive on staying with the latest version, because you can run into issues in the other direction where people are on latest and having issues with previous versions.  In the general sense - I'd really reccomend staying on top of TypeScript releases with a tool like [renovate](https://renovatebot.com).  Hope this helps!
